# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2021-09-08 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZXYstudent',
            fields=[
                ('s_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='学号')),
                ('s_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('s_email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('s_password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_active', models.BooleanField(default=False, verbose_name='账号是否已激活')),
                ('is_delete', models.BooleanField(default=False, verbose_name='账号是否已删除')),
            ],
            options={
                'verbose_name': '学生账号管理',
                'verbose_name_plural': '学生账号管理',
                'db_table': 'zxy_student',
            },
        ),
        migrations.CreateModel(
            name='ZXYteacher',
            fields=[
                ('t_id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='职工号')),
                ('t_name', models.CharField(max_length=32, verbose_name='姓名')),
                ('t_email', models.CharField(max_length=64, verbose_name='邮箱')),
                ('t_password', models.CharField(max_length=256, verbose_name='密码')),
                ('is_active', models.BooleanField(default=False, verbose_name='账号是否已激活')),
                ('is_delete', models.BooleanField(default=False, verbose_name='账号是否已删除')),
            ],
            options={
                'verbose_name': '教师账号管理',
                'verbose_name_plural': '教师账号管理',
                'db_table': 'zxy_teacher',
            },
        ),
    ]
